// Generated by CoffeeScript 1.4.0
(function() {

  define(['./ometa-base', './lib', './bs-dentparser', './bs-semactionparser', './bs-ometa-optimizer', './bs-ometa-compiler', './bs-metacoffee-compiler'], function(OMeta, OMLib, BSDentParser, BSOmetaCompiler, BSOmetaOptimizer, BSMetaCoffeeCompiler) {
    return {
      OMeta: OMeta,
      OMLib: OMLib,
      BSMetaCoffeeParser: BSMetaCoffeeCompiler.BSMetaCoffeeParser,
      BSMetaCoffeeTranslator: BSMetaCoffeeCompiler.BSMetaCoffeeTranslator
    };
  });

}).call(this);
