// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!../src/ometa-base', 'cs!../src/lib', '../bin/bs-dentparser', '../bin/bs-semactionparser', '../bin/bs-ometa-optimizer', '../bin/bs-ometa-compiler', '../bin/bs-metacoffee-compiler'], function(OMeta, OMLib, BSDentParser, BSOmetaCompiler, BSOmetaOptimizer, BSMetaCoffeeCompiler) {
    return {
      OMeta: OMeta,
      OMLib: OMLib,
      BSMetaCoffeeParser: BSMetaCoffeeCompiler.BSMetaCoffeeParser,
      BSMetaCoffeeTranslator: BSMetaCoffeeCompiler.BSMetaCoffeeTranslator
    };
  });

}).call(this);
