// Generated by CoffeeScript 1.4.0
(function() {
  var requirejs;

  requirejs = require('requirejs');

  requirejs.config({
    baseUrl: __dirname,
    nodeRequire: require,
    paths: {
      cs: '../lib/requirejs/cs',
      'coffee-script': '../lib/cs/coffee-script'
    }
  });

  requirejs(['cs!../src/metacoffee', 'cs!../workspace/ErrorHandler'], function(MetaCoffee, ErrorHandler) {
    var BSMetaCoffeeParser, BSMetaCoffeeTranslator, compileSource;
    BSMetaCoffeeParser = MetaCoffee.BSMetaCoffeeParser;
    BSMetaCoffeeTranslator = MetaCoffee.BSMetaCoffeeTranslator;
    return module.exports = compileSource = function(sourceCode) {
      var result, tree;
      try {
        tree = BSMetaCoffeeParser.matchAll(sourceCode, "topLevel", void 0, function(m, i) {
          var handled;
          handled = ErrorHandler.handle(m, i);
          throw new Error("Error at line: " + handled.lineNumber + "\n\n" + ErrorHandler.bottomErrorArrow(handled));
        });
        result = BSMetaCoffeeTranslator.matchAll(tree, "trans", void 0, function(m, i) {}, (function() {
          throw new Error("Translation error - please tell Alex about this!");
        })());
      } catch (e) {
        return e.toString();
      }
      return result;
    };
  });

}).call(this);
